create table studies(pname varchar2(38),splace varchar2(38),course varchar(38),ccost int);
describe studies;
select*from studies;
insert into studies(pname,splace,course,ccost)values('anand','sabari','PGDCA','4500');
insert into studies(pname,splace,course,ccost)values('Ramesh','CSDI','DCA','7200');
insert into studies(pname,splace,course,ccost)values('Jayakumar','BITS','MCA','4200');
insert into studies(pname,splace,course,ccost)values('Rahul','sabari','PGDCA','4500');
insert into studies(pname,splace,course,ccost)values('mani','BDRS','DC','4200');
insert into studies(pname,splace,course,ccost)values('gowtham','Apple','PGDCA','4500');
insert into studies(pname,splace,course,ccost)values('vinoth','BRILLIAN','DAP',null);
insert into studies(pname,splace,course,ccost)values('muness','HDCP','MCA',null);
delete from studies where pname='muness';
insert into studies(pname,splace,course,ccost)values('hari','HDCP','MCA','1000');
insert into studies(pname,splace,course,ccost)values('munis','apple','MCA',null);
select*from studies;
alter table studies add Grade varchar2(38) default('s');
alter table studies add Gender varchar2(32)default('male');
insert into studies (pname,splace,course,ccost,Grade,Gender)values('alia','BDRS','MCA',7000,null,'female');

insert into studies (pname,splace,course,ccost,Grade,Gender)values('sanon','BDRS','MCA',5000,'b','female');
alter table studies add  DOB date;
update studies set dob='29-07-1999' where pname='anand';
update studies set dob='25-04-1996' where pname='mani';
update studies set dob='18-07-1998' where pname='hari';
update studies set dob='20-03-1999' where pname='vinoth';
update studies set dob='12-07-1997' where pname='munis';
update studies set dob='29-07-1992' where pname='sanon';
update studies set dob='09-07-1995' where pname='alia';
alter table studies add DOJ date;
select*from studies;
update studies set doj='21/apr/2019' where pname='anand';
update studies set doj='29-apr-1999' where pname='mani';
update studies set doj='29-june-2019' where splace='bits';
update studies set doj='29-july-2019' where pname='ramesh';
update studies set ccost=7777 where pname='vinoth';
update studies set doj='11-07-1999' where pname='gowtham';
update studies set doj='11-april-1888' where pname='Jayakumar';
delete from studies where pname='jayakumar';
desc studies;
update studies set ccost=2348 where pname='munis';
update studies set grade='s' where pname='alia';
select pname,splace from studies;  //select the number of column
rollback;
